version: 2.1
  jobs:
    install_autheticate:
      docker:
        - image: 'cimg/node:12.6'
      steps:
        - apex/setup:
            defaultusername: sample@email.com
  orbs:
    apex: circleci/salesforce-apex@x.y
  version: 2.1
  workflows:
    basic_test:
      jobs:
        - install_authenticate

