version: 2.1
orbs:
  apex: circleci/salesforce-apex@1.0.1

jobs: 
  install_authenticate:
    docker:
      - image: cimg/node:14.5
    steps:
      - checkout
      - apex/setup:
          defaultusername: shai.l@outlook.com
      - run:
          name: Check Auth List
          command: sfdx force:auth:list

workflows:
    basic-test:
        jobs:
          - install_authenticate
